version: '3.9'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: teamb
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: teamb1111
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    container_name: server
    build: .  # Dockerfile이 위치한 디렉터리를 가리키며, 일반적으로 Dockerfile의 이름을 지정하지 않습니다.
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
    depends_on:
      mysql:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
