version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: teamb
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  server:
    container_name: server
    build: .  # Dockerfile이 위치한 디렉터리를 가리키며, 일반적으로 Dockerfile의 이름을 지정하지 않습니다.
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
