spring:
  datasource:
    # 추후 RDS 설정에 맞게 변경
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/teamb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create     # 추후 validate 옵션으로 변경
    properties:
      hibernate:
        format_sql: true